"""SentinelOne PowerQuery hunting rules generated from the LOLRMM corpus.

Two rules, one YAML file each, rewritten on every `lolrmm refresh` so the
indicator lists never drift from upstream:

- process: `src.process.displayName` against every application alias
  (the same set as applications.csv / application_name_lower).
- url:     `url.address` against every Network domain artifact, normalised
  into literal substrings that PowerQuery `contains` can actually match.

The file layout is Sigma-shaped (title/id/description/tags/logsource/
falsepositives/level) so the query travels with its metadata; the detection
itself is a verbatim PowerQuery under `query:`.
"""

from __future__ import annotations

import json
import re
from collections.abc import Callable
from dataclasses import dataclass
from datetime import date
from pathlib import Path

import yaml

from . import applications as apps_mod
from . import indicators as indicators_mod
from .models import Tool

RULE_DATE = "2026-09-09"  # first release of the generated rules; `modified` tracks list changes
AUTHOR = "InfoSecJay (generated by lolrmm-artifacts)"
REFERENCES = (
    "https://lolrmm.io",
    "https://github.com/magicsword-io/LOLRMM",
    "https://github.com/InfoSecJay/lolrmm-artifacts",
)

# --- URL indicator normalisation -------------------------------------------

# Tokens PowerQuery `contains` would take literally but LOLRMM meant as a
# pattern: glob stars, `?`, regex character classes / quantifiers / groups.
_PATTERN_TOKEN = re.compile(r"\*|\?|\[[^\]]*\]|\{[^}]*\}|\([^)]*\)")
_SCHEME = re.compile(r"^[a-z][a-z0-9+.-]*://", re.IGNORECASE)
_PORT = re.compile(r":\d+$")
# What survives must look like `[.]host.tld[/path]` - a literal a URL can contain.
# `_` is not valid in a hostname but shows up in the wild (upload_data.qq.com).
_VALID = re.compile(r"^\.?[a-z0-9_-]+(\.[a-z0-9_-]+)+(/[^\s'\"*?\[\]{}()]*)?$")


def url_substring(raw: str) -> str | None:
    """Turn one LOLRMM domain entry into a literal `contains` operand, or None.

    - `*.anydesk.com`                          -> `.anydesk.com` (subdomain suffix)
    - `*ammyy.com`                             -> `ammyy.com`
    - `agents*-cloud.acronis.com`              -> `-cloud.acronis.com` (literal tail
                                                  after the last wildcard/regex token)
    - `relay-[a-f0-9]{8}.net.anydesk.com:443`  -> `.net.anydesk.com`
    - `https://github.com/x/y`                 -> `github.com/x/y`
    - `user_managed`                           -> None (not a hostname)

    The host part is lowercased (hostnames are case-insensitive); any path is
    kept as-is.
    """
    s = _SCHEME.sub("", raw.strip())
    s = _PATTERN_TOKEN.split(s)[-1]
    host, slash, path = s.partition("/")
    host = _PORT.sub("", host.lower())
    s = host + slash + path
    return s if _VALID.match(s) else None


# --- value collectors --------------------------------------------------------


def process_values(tools: list[Tool]) -> tuple[list[str], dict]:
    """Lower-cased application aliases, deduped across tools (applications.csv col B)."""
    values = sorted({r.application_name_lower for r in apps_mod.collect(tools)})
    return values, {"source": "applications.csv (application_name_lower)"}


def url_values(tools: list[Tool]) -> tuple[list[str], dict]:
    """Normalised domain substrings plus an audit trail of what was rewritten/dropped."""
    values: set[str] = set()
    rewritten: list[str] = []
    dropped: list[str] = []
    for raw in indicators_mod.collect(tools, "domain"):
        sub = url_substring(raw)
        if sub is None:
            dropped.append(raw)
            continue
        values.add(sub)
        # `*.x` -> `.x` is the expected transform; only report anything beyond that.
        if sub.lower() != raw.lower().lstrip("*"):
            rewritten.append(f"{raw} -> {sub}")
    meta = {"source": "indicators/domain.txt", "rewritten": rewritten, "dropped": dropped}
    return sorted(values), meta


# --- rule specs ----------------------------------------------------------------


@dataclass(frozen=True)
class RuleSpec:
    key: str
    filename: str
    title: str
    id: str
    description: str
    tags: tuple[str, ...]
    category: str
    falsepositives: tuple[str, ...]
    level: str
    head: str  # query text before the value list
    tail: str  # query text after the value list
    collect: Callable[[list[Tool]], tuple[list[str], dict]]


_GROUP_METRICS = (
    "    count = count(),\n"
    "    est_hosts = estimate_distinct(endpoint.name),\n"
    "    est_users = estimate_distinct(src.process.user),\n"
    "    sites = array_agg_distinct(site.name)"
)

PROCESS_RULE = RuleSpec(
    key="process",
    filename="lolrmm_process.yml",
    title="LOLRMM Remote Management Tool Process Activity",
    id="93da48e8-5d1e-4b3b-a767-9c4aafe07495",
    description=(
        "Hunting query. Aggregates SentinelOne process-creation events whose display\n"
        "name contains any application alias tracked by LOLRMM (tool name, PE product,\n"
        "PE description, PE original filename - the same set as applications.csv).\n"
        "Scope is deliberately broad: every LOLRMM tool, RMM and RAT alike. Matching is\n"
        "substring, so triage by publisher from the grouped output rather than alerting\n"
        "per event."
    ),
    tags=("attack.command_and_control", "attack.t1219"),
    category="process_creation",
    falsepositives=(
        "Sanctioned RMM tooling. Baseline the src.process.publisher values in the results "
        "and add a filter for approved publishers.",
        "Short or dictionary-word aliases (level, synergy, terminals, vnc) substring-match "
        "unrelated software. Check src.process.name before acting.",
    ),
    level="low",
    head="event.type='Process Creation'\n| filter src.process.displayName contains (\n",
    tail=(
        "  )\n"
        "| group\n"
        f"{_GROUP_METRICS}\n"
        "  by src.process.displayName, src.process.publisher, src.process.name\n"
    ),
    collect=process_values,
)

URL_RULE = RuleSpec(
    key="url",
    filename="lolrmm_url.yml",
    title="LOLRMM Remote Management Tool URL Activity",
    id="063e2aad-8dff-45f2-8940-5949c040b48d",
    description=(
        "Hunting query. Aggregates SentinelOne URL events whose address contains any\n"
        "Network domain artifact tracked by LOLRMM. Wildcard entries (*.example.com)\n"
        "become suffix substrings (.example.com); regex and mid-string wildcards are\n"
        "reduced to their literal tail (listed under generated.rewritten). Scope is\n"
        "deliberately broad: every LOLRMM tool. Output is grouped by parsed domain and\n"
        "requesting process so vendor sites and agent infrastructure separate cleanly."
    ),
    tags=("attack.command_and_control", "attack.t1219", "attack.t1071.001"),
    category="url",
    falsepositives=(
        "Browsing to vendor marketing or documentation pages. Several LOLRMM entries are "
        "website paths, not agent infrastructure.",
        "Apex entries without a leading dot (level.io, set.me, remote.it) substring-match "
        "unrelated hosts such as notlevel.io.",
        "Literal tails kept from wildcard entries (see generated.rewritten) can be shared "
        "cloud suffixes that match any tenant on that service.",
    ),
    level="low",
    head="event.category='url'\n| filter url.address contains (\n",
    tail=(
        "  )\n"
        "| let domain = net_url_domain(url.address)\n"
        "| group\n"
        f"{_GROUP_METRICS},\n"
        "    urls = array_agg(url.address)\n"
        "  by domain, src.process.displayName, src.process.publisher\n"
    ),
    collect=url_values,
)

RULES: tuple[RuleSpec, ...] = (PROCESS_RULE, URL_RULE)


# --- rendering ---------------------------------------------------------------------


def _quote(value: str) -> str:
    """PowerQuery string literal: single-quoted unless the value holds a single quote."""
    if "'" not in value:
        return f"'{value}'"
    return '"' + value.replace('"', '\\"') + '"'


def build_query(spec: RuleSpec, values: list[str]) -> str:
    body = ",\n".join(f"    {_quote(v)}" for v in values)
    return f"{spec.head}{body}\n{spec.tail}"


def _block(text: str, indent: str = "  ") -> list[str]:
    return [f"{indent}{line}" if line else "" for line in text.rstrip("\n").split("\n")]


def _yaml_list(key: str, items: list[str], indent: str = "") -> list[str]:
    if not items:
        return [f"{indent}{key}: []"]
    quoted = [json.dumps(item, ensure_ascii=False) for item in items]
    return [f"{indent}{key}:"] + [f"{indent}  - {q}" for q in quoted]


def render(spec: RuleSpec, query: str, generated: dict, modified: str) -> str:
    """Sigma-shaped YAML with the PowerQuery as a literal block. Hand-rendered so
    the layout (comment header, block scalar, key order) is stable for git diffs."""
    lines: list[str] = [
        "# Generated by `lolrmm refresh` from the LOLRMM corpus. Do not edit by hand;",
        "# the indicator list is rewritten on every refresh so it tracks upstream.",
        f"title: {spec.title}",
        f"id: {spec.id}",
        "status: experimental",
        "description: |",
        *_block(spec.description),
        f"author: {AUTHOR}",
        f"date: {RULE_DATE}",
        f"modified: {modified}",
        "references:",
        *[f"  - {r}" for r in REFERENCES],
        "tags:",
        *[f"  - {t}" for t in spec.tags],
        "logsource:",
        "  product: sentinelone",
        "  service: powerquery",
        f"  category: {spec.category}",
        "generated:",
    ]
    for key, val in generated.items():
        if isinstance(val, list):
            lines += _yaml_list(key, val, indent="  ")
        else:
            lines.append(f"  {key}: {val}")
    lines += [
        "query: |",
        *_block(query),
        "falsepositives:",
        *[f"  - {fp}" for fp in spec.falsepositives],
        f"level: {spec.level}",
    ]
    return "\n".join(lines) + "\n"


def _carry_modified(previous_text: str | None, query: str, today: str) -> str:
    """Keep the previous `modified` date unless the query text changed, so a
    daily refresh with no new indicators leaves the file byte-identical."""
    if not previous_text:
        return today
    try:
        prev = yaml.safe_load(previous_text)
    except yaml.YAMLError:
        return today
    if isinstance(prev, dict) and prev.get("modified"):
        if str(prev.get("query", "")).rstrip() == query.rstrip():
            return str(prev["modified"])
    return today


def build(spec: RuleSpec, tools: list[Tool]) -> tuple[str, dict]:
    """Return (query text, `generated:` metadata) for one rule."""
    values, meta = spec.collect(tools)
    generated = {"source": meta.pop("source"), "indicators": len(values), "tools": len(tools)}
    generated.update(meta)
    return build_query(spec, values), generated


def write_rules(tools: list[Tool], out_dir: Path, today: str | None = None) -> dict[str, Path]:
    today = today or date.today().isoformat()
    out_dir.mkdir(parents=True, exist_ok=True)
    paths: dict[str, Path] = {}
    for spec in RULES:
        query, generated = build(spec, tools)
        path = out_dir / spec.filename
        previous = path.read_text(encoding="utf-8") if path.exists() else None
        text = render(spec, query, generated, _carry_modified(previous, query, today))
        # LF on every platform so a local run and the Linux CI run produce the same bytes.
        path.write_text(text, encoding="utf-8", newline="\n")
        paths[spec.key] = path
    return paths
